"""
planner.py - Code-to-Plan Converter for Safe Pandas Execution

Converts simple pandas-like code strings (as generated by the AI model)
into structured execution plan dictionaries that can be passed to
safe_exec.execute_plan().

This module uses regex-based pattern matching to parse code strings.
It does NOT use exec() or eval().

Supported patterns:
  - df.groupby('col')['agg_col'].mean()
  - df.groupby('col').agg({'col': 'func'})
  - df.groupby(['col1','col2'])['agg_col'].sum()
  - df['column'].mean()
  - df.column.mean()
  - result = df[df['col'] == 'value']
  - result = df[df['col'] == number]

Usage:
    from planner import code_to_plan
    plan = code_to_plan("df.groupby('sender_bank')['amount_inr'].mean()")
    # => {"op": "groupby", "by": ["sender_bank"], "agg": {"amount_inr": "mean"}}
"""

import re
from typing import Any, Dict, Optional


# ---------------------------------------------------------------------------
# Allowed aggregation function names (whitelist)
# ---------------------------------------------------------------------------

_ALLOWED_AGG_FUNCS = {
    "sum", "mean", "count", "min", "max",
    "median", "std", "var", "nunique", "first", "last", "size",
}


# ---------------------------------------------------------------------------
# Internal pattern matchers
# ---------------------------------------------------------------------------

def _try_groupby_bracket_agg(code: str) -> Optional[Dict[str, Any]]:
    """
    Match: df.groupby('col')['agg_col'].func()
    Match: df.groupby(['col1','col2'])['agg_col'].func()

    Examples:
        df.groupby('sender_bank')['amount_inr'].mean()
        df.groupby(['sender_bank', 'device_type'])['amount_inr'].sum()
    """
    pattern = (
        r"df\.groupby\("
        r"(\[.*?\]|['\"](\w+)['\"])"     # group 1: full arg, group 2: single col
        r"\)\[(?:['\"])(\w+)(?:['\"])\]"  # group 3: agg column
        r"\.(\w+)\(\)"                     # group 4: agg function
    )
    match = re.search(pattern, code)
    if not match:
        return None

    full_arg = match.group(1)
    single_col = match.group(2)
    agg_column = match.group(3)
    agg_func = match.group(4)

    if agg_func not in _ALLOWED_AGG_FUNCS:
        return None

    # Parse group-by columns
    if single_col:
        by_cols = [single_col]
    else:
        by_cols = re.findall(r"['\"](\w+)['\"]", full_arg)

    return {
        "op": "groupby",
        "by": by_cols,
        "agg": {agg_column: agg_func},
    }


def _try_groupby_dot_agg(code: str) -> Optional[Dict[str, Any]]:
    """
    Match: df.groupby('col').agg({'col': 'func'})
    Match: df.groupby('col').agg({'col1': 'func1', 'col2': 'func2'})

    Examples:
        df.groupby('sender_bank').agg({'amount_inr': 'mean'})
        df.groupby('sender_state').agg({'amount_inr': 'sum', 'fraud_flag': 'mean'})
    """
    pattern = (
        r"df\.groupby\("
        r"(\[.*?\]|['\"](\w+)['\"])"   # group 1: full arg, group 2: single col
        r"\)\.agg\(\{(.*?)\}\)"         # group 3: dict contents
    )
    match = re.search(pattern, code)
    if not match:
        return None

    full_arg = match.group(1)
    single_col = match.group(2)
    dict_contents = match.group(3)

    # Parse group-by columns
    if single_col:
        by_cols = [single_col]
    else:
        by_cols = re.findall(r"['\"](\w+)['\"]", full_arg)

    # Parse agg dict: 'col': 'func' pairs
    agg_pairs = re.findall(r"['\"](\w+)['\"]:\s*['\"](\w+)['\"]", dict_contents)
    if not agg_pairs:
        return None

    agg_dict = {}
    for col, func in agg_pairs:
        if func not in _ALLOWED_AGG_FUNCS:
            return None
        agg_dict[col] = func

    return {
        "op": "groupby",
        "by": by_cols,
        "agg": agg_dict,
    }


def _try_column_agg(code: str) -> Optional[Dict[str, Any]]:
    """
    Match: df['column'].func()
    Match: df.column.func()

    Examples:
        df['amount_inr'].mean()
        df.amount_inr.mean()
    """
    # Bracket notation: df['column'].func()
    pattern_bracket = r"df\[['\"](\w+)['\"]\]\.(\w+)\(\)"
    match = re.search(pattern_bracket, code)
    if match:
        column = match.group(1)
        func = match.group(2)
        if func in _ALLOWED_AGG_FUNCS:
            return {"op": func, "column": column}
        return None

    # Dot notation: df.column.func()
    pattern_dot = r"df\.(\w+)\.(\w+)\(\)"
    match = re.search(pattern_dot, code)
    if match:
        column = match.group(1)
        func = match.group(2)
        # Exclude false positives like df.groupby(...)
        if column in ("groupby", "agg", "merge", "join", "apply", "reset_index"):
            return None
        if func in _ALLOWED_AGG_FUNCS:
            return {"op": func, "column": column}

    return None


def _try_filter_equality(code: str) -> Optional[Dict[str, Any]]:
    """
    Match: df[df['col'] == 'value']
    Match: df[df['col'] == number]

    Examples:
        df[df['transaction_status'] == 'FAILED']
        df[df['fraud_flag'] == 1]
    """
    # String value filter
    pattern_str = r"df\[df\[['\"](\w+)['\"]\]\s*==\s*['\"]([^'\"]+)['\"]\]"
    match = re.search(pattern_str, code)
    if match:
        return {
            "op": "filter",
            "column": match.group(1),
            "value": match.group(2),
        }

    # Numeric value filter
    pattern_num = r"df\[df\[['\"](\w+)['\"]\]\s*==\s*([0-9]+(?:\.[0-9]+)?)\]"
    match = re.search(pattern_num, code)
    if match:
        raw_value = match.group(2)
        value = float(raw_value) if "." in raw_value else int(raw_value)
        return {
            "op": "filter",
            "column": match.group(1),
            "value": value,
        }

    return None


def _try_value_counts(code: str) -> Optional[Dict[str, Any]]:
    """
    Match: df['column'].value_counts()

    Translates to a groupby + count plan.

    Example:
        df['sender_bank'].value_counts()
    """
    pattern = r"df\[['\"](\w+)['\"]\]\.value_counts\(\)"
    match = re.search(pattern, code)
    if match:
        column = match.group(1)
        return {
            "op": "groupby",
            "by": [column],
            "agg": {column: "count"},
        }
    return None


# ---------------------------------------------------------------------------
# Ordered matcher pipeline
# ---------------------------------------------------------------------------

_MATCHERS = [
    _try_groupby_bracket_agg,
    _try_groupby_dot_agg,
    _try_value_counts,
    _try_filter_equality,
    _try_column_agg,
]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def code_to_plan(code: str) -> Dict[str, Any]:
    """
    Convert a pandas code string into a structured execution plan.

    Scans the input code against a series of regex-based pattern
    matchers (in priority order) and returns the first matching plan.

    Args:
        code: A string of pandas code, typically AI-generated.
              May contain assignment prefixes like "result = ..."
              which are stripped before matching.

    Returns:
        A dictionary describing the operation. The "op" key indicates
        the operation type.

    Raises:
        ValueError: If the code does not match any supported pattern.

    Examples:
        >>> code_to_plan("result = df.groupby('sender_bank')['amount_inr'].mean()")
        {"op": "groupby", "by": ["sender_bank"], "agg": {"amount_inr": "mean"}}

        >>> code_to_plan("result = df['amount_inr'].mean()")
        {"op": "mean", "column": "amount_inr"}

        >>> code_to_plan("result = df[df['transaction_status'] == 'FAILED']")
        {"op": "filter", "column": "transaction_status", "value": "FAILED"}

        >>> code_to_plan("result = df['sender_bank'].value_counts()")
        {"op": "groupby", "by": ["sender_bank"], "agg": {"sender_bank": "count"}}
    """
    if not isinstance(code, str) or not code.strip():
        raise ValueError("code must be a non-empty string")

    # Normalize: strip assignment prefix, whitespace, and trailing semicolons
    cleaned = code.strip().rstrip(";").strip()
    if "=" in cleaned:
        # Take only the right-hand side of the first assignment
        _, _, cleaned = cleaned.partition("=")
        cleaned = cleaned.strip()

    for matcher in _MATCHERS:
        plan = matcher(cleaned)
        if plan is not None:
            return plan

    raise ValueError(
        f"Could not parse code into a supported plan.\n"
        f"Code: {code}\n"
        f"Supported patterns:\n"
        f"  - df.groupby('col')['agg_col'].func()\n"
        f"  - df.groupby('col').agg({{'col': 'func'}})\n"
        f"  - df['column'].func()\n"
        f"  - df[df['col'] == value]\n"
        f"  - df['col'].value_counts()"
    )
